set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_SUPER_USER" <<-EOSQL
	CREATE ROLE IF NOT EXISTS "${POSTGRES_USER}"
		PASSWORD "${POSTGRES_PASSWORD}"
		NOSUPERUSER
		NOCREATEDB
		NOCREATEROLE
		INHERIT LOGIN;

	CREATE SCHEMA IF NOT EXISTS "${POSTGRES_DB}";

	\c "${POSTGRES_DB}" "${POSTGRES_USER}";

	\i /scripts/database/sql/01-create-tables.sql

	GRANT ALL PRIVILEGES
		ON SCHEMA "${POSTGRES_DATABASE}"
		TO "${POSTGRES_USER}";
EOSQL