CREATE DATABASE IF NOT EXISTS tcc_database;

\c tcc_database;

CREATE TABLE _user_account (
  private_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username     VARCHAR(40) NOT NULL CHECK (username <> ''),
  email        VARCHAR(100) NOT NULL UNIQUE CHECK (email <> ''),
  passwd       SERIAL NOT NULL,
  photo        TEXT NULL
);

CREATE TABLE user_client (
  private_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  public_id    SERIAL UNIQUE,
);

CREATE TABLE user_employee (
  private_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  public_id    SERIAL UNIQUE,
);

CREATE TABLE _address (
  private_id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  zip_code     CHAR(8) NOT NULL,
  state        CHAR(2) NOT NULL,
  city         TEXT NOT NULL,
  neighborhood TEXT NOT NULL,
  street       TEXT NOT NULL
);

CREATE TABLE employee_service ();

CREATE TABLE service_category ();

CREATE TABLE service_announcement ();

CREATE TABLE service_user_favorite ();

CREATE TABLE service_review ();

CREATE TABLE client_review ();